language: node_js
sudo: false
node_js:
  - 8

cache: yarn

install:
  - yarn install

script:
  - yarn run lint && yarn run cover

after_success:
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
